// Standardni popis 114 sura — broj, bosanski naziv (uobičajena
// transliteracija, ista konvencija kao nazivi Excel fajlova u pipeline-u),
// i broj ajeta. Ovo je opšte poznata kur'anska metapodataka, nezavisna od
// QAC pipeline-a; kasnije zamjenjuje `surahs` tabela iz Supabase baze.

export interface SurahMeta {
  id: number;
  nameBs: string;
  ayahCount: number;
}

export const SURAHS: SurahMeta[] = [
  { id: 1, nameBs: "El-Fatiha", ayahCount: 7 },
  { id: 2, nameBs: "El-Bekara", ayahCount: 286 },
  { id: 3, nameBs: "Alu Imran", ayahCount: 200 },
  { id: 4, nameBs: "En-Nisa", ayahCount: 176 },
  { id: 5, nameBs: "El-Maida", ayahCount: 120 },
  { id: 6, nameBs: "El-En'am", ayahCount: 165 },
  { id: 7, nameBs: "El-A'raf", ayahCount: 206 },
  { id: 8, nameBs: "El-Enfal", ayahCount: 75 },
  { id: 9, nameBs: "Et-Tevba", ayahCount: 129 },
  { id: 10, nameBs: "Junus", ayahCount: 109 },
  { id: 11, nameBs: "Hud", ayahCount: 123 },
  { id: 12, nameBs: "Jusuf", ayahCount: 111 },
  { id: 13, nameBs: "Er-Ra'd", ayahCount: 43 },
  { id: 14, nameBs: "Ibrahim", ayahCount: 52 },
  { id: 15, nameBs: "El-Hidžr", ayahCount: 99 },
  { id: 16, nameBs: "En-Nahl", ayahCount: 128 },
  { id: 17, nameBs: "El-Isra", ayahCount: 111 },
  { id: 18, nameBs: "El-Kehf", ayahCount: 110 },
  { id: 19, nameBs: "Merjem", ayahCount: 98 },
  { id: 20, nameBs: "Ta-ha", ayahCount: 135 },
  { id: 21, nameBs: "El-Enbija", ayahCount: 112 },
  { id: 22, nameBs: "El-Hadždž", ayahCount: 78 },
  { id: 23, nameBs: "El-Mu'minun", ayahCount: 118 },
  { id: 24, nameBs: "En-Nur", ayahCount: 64 },
  { id: 25, nameBs: "El-Furkan", ayahCount: 77 },
  { id: 26, nameBs: "Eš-Šu'ara", ayahCount: 227 },
  { id: 27, nameBs: "En-Neml", ayahCount: 93 },
  { id: 28, nameBs: "El-Kasas", ayahCount: 88 },
  { id: 29, nameBs: "El-Ankebut", ayahCount: 69 },
  { id: 30, nameBs: "Er-Rum", ayahCount: 60 },
  { id: 31, nameBs: "Lukman", ayahCount: 34 },
  { id: 32, nameBs: "Es-Sedžda", ayahCount: 30 },
  { id: 33, nameBs: "El-Ahzab", ayahCount: 73 },
  { id: 34, nameBs: "Sebe'", ayahCount: 54 },
  { id: 35, nameBs: "Fatir", ayahCount: 45 },
  { id: 36, nameBs: "Ja-sin", ayahCount: 83 },
  { id: 37, nameBs: "Es-Saffat", ayahCount: 182 },
  { id: 38, nameBs: "Sad", ayahCount: 88 },
  { id: 39, nameBs: "Ez-Zumer", ayahCount: 75 },
  { id: 40, nameBs: "Gafir", ayahCount: 85 },
  { id: 41, nameBs: "Fussilet", ayahCount: 54 },
  { id: 42, nameBs: "Eš-Šura", ayahCount: 53 },
  { id: 43, nameBs: "Ez-Zuhruf", ayahCount: 89 },
  { id: 44, nameBs: "Ed-Duhan", ayahCount: 59 },
  { id: 45, nameBs: "El-Džasija", ayahCount: 37 },
  { id: 46, nameBs: "El-Ahkaf", ayahCount: 35 },
  { id: 47, nameBs: "Muhammed", ayahCount: 38 },
  { id: 48, nameBs: "El-Feth", ayahCount: 29 },
  { id: 49, nameBs: "El-Hudžurat", ayahCount: 18 },
  { id: 50, nameBs: "Kaf", ayahCount: 45 },
  { id: 51, nameBs: "Ez-Zarijat", ayahCount: 60 },
  { id: 52, nameBs: "Et-Tur", ayahCount: 49 },
  { id: 53, nameBs: "En-Nedžm", ayahCount: 62 },
  { id: 54, nameBs: "El-Kamer", ayahCount: 55 },
  { id: 55, nameBs: "Er-Rahman", ayahCount: 78 },
  { id: 56, nameBs: "El-Vakia", ayahCount: 96 },
  { id: 57, nameBs: "El-Hadid", ayahCount: 29 },
  { id: 58, nameBs: "El-Mudžadela", ayahCount: 22 },
  { id: 59, nameBs: "El-Hašr", ayahCount: 24 },
  { id: 60, nameBs: "El-Mumtehina", ayahCount: 13 },
  { id: 61, nameBs: "Es-Saff", ayahCount: 14 },
  { id: 62, nameBs: "El-Džumu'a", ayahCount: 11 },
  { id: 63, nameBs: "El-Munafikun", ayahCount: 11 },
  { id: 64, nameBs: "Et-Tegabun", ayahCount: 18 },
  { id: 65, nameBs: "Et-Talak", ayahCount: 12 },
  { id: 66, nameBs: "Et-Tahrim", ayahCount: 12 },
  { id: 67, nameBs: "El-Mulk", ayahCount: 30 },
  { id: 68, nameBs: "El-Kalem", ayahCount: 52 },
  { id: 69, nameBs: "El-Hakka", ayahCount: 52 },
  { id: 70, nameBs: "El-Mearidž", ayahCount: 44 },
  { id: 71, nameBs: "Nuh", ayahCount: 28 },
  { id: 72, nameBs: "El-Džinn", ayahCount: 28 },
  { id: 73, nameBs: "El-Muzzemmil", ayahCount: 20 },
  { id: 74, nameBs: "El-Muddessir", ayahCount: 56 },
  { id: 75, nameBs: "El-Kijama", ayahCount: 40 },
  { id: 76, nameBs: "El-Insan", ayahCount: 31 },
  { id: 77, nameBs: "El-Murselat", ayahCount: 50 },
  { id: 78, nameBs: "En-Nebe", ayahCount: 40 },
  { id: 79, nameBs: "En-Nazi'at", ayahCount: 46 },
  { id: 80, nameBs: "Abese", ayahCount: 42 },
  { id: 81, nameBs: "Et-Tekvir", ayahCount: 29 },
  { id: 82, nameBs: "El-Infitar", ayahCount: 19 },
  { id: 83, nameBs: "El-Mutaffifin", ayahCount: 36 },
  { id: 84, nameBs: "El-Inšikak", ayahCount: 25 },
  { id: 85, nameBs: "El-Burudž", ayahCount: 22 },
  { id: 86, nameBs: "Et-Tarik", ayahCount: 17 },
  { id: 87, nameBs: "El-A'la", ayahCount: 19 },
  { id: 88, nameBs: "El-Gašija", ayahCount: 26 },
  { id: 89, nameBs: "El-Fedžr", ayahCount: 30 },
  { id: 90, nameBs: "El-Beled", ayahCount: 20 },
  { id: 91, nameBs: "Eš-Šems", ayahCount: 15 },
  { id: 92, nameBs: "El-Lejl", ayahCount: 21 },
  { id: 93, nameBs: "Ed-Duha", ayahCount: 11 },
  { id: 94, nameBs: "Eš-Šerh", ayahCount: 8 },
  { id: 95, nameBs: "Et-Tin", ayahCount: 8 },
  { id: 96, nameBs: "El-Alek", ayahCount: 19 },
  { id: 97, nameBs: "El-Kadr", ayahCount: 5 },
  { id: 98, nameBs: "El-Bejjina", ayahCount: 8 },
  { id: 99, nameBs: "Ez-Zilzal", ayahCount: 8 },
  { id: 100, nameBs: "El-Adijat", ayahCount: 11 },
  { id: 101, nameBs: "El-Karia", ayahCount: 11 },
  { id: 102, nameBs: "Et-Tekasur", ayahCount: 8 },
  { id: 103, nameBs: "El-Asr", ayahCount: 3 },
  { id: 104, nameBs: "El-Humeza", ayahCount: 9 },
  { id: 105, nameBs: "El-Fil", ayahCount: 5 },
  { id: 106, nameBs: "Kurejš", ayahCount: 4 },
  { id: 107, nameBs: "El-Maun", ayahCount: 7 },
  { id: 108, nameBs: "El-Kevser", ayahCount: 3 },
  { id: 109, nameBs: "El-Kafirun", ayahCount: 6 },
  { id: 110, nameBs: "En-Nasr", ayahCount: 3 },
  { id: 111, nameBs: "El-Leheb", ayahCount: 5 },
  { id: 112, nameBs: "El-Ihlas", ayahCount: 4 },
  { id: 113, nameBs: "El-Felek", ayahCount: 5 },
  { id: 114, nameBs: "En-Nas", ayahCount: 6 },
];

// Sure za koje trenutno postoji uvezen APP_READY fajl (privremeni JSON
// fixture-i u src/lib/fixtures/). Ažurira se kako pipeline uvozi nove sure.
export const AVAILABLE_SURAH_IDS = new Set<number>([
  1, 78, 79, 81, 82, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
  114,
]);
